const configData = [
    {
        id: 1,
        enableHttps: 1,
        storeCountry: 42,
        stateRegion: 2,
        city: '',
        streetAddress: '',
        zipPostalCode: '',
        allCountries: ["Afghanistan", "Åland Islands", "Albania", "Algeria", "American Samoa", "Andorra", "Angola", "Anguilla", "Antarctica", "Antigua &amp; Barbuda", "Argentina", "Armenia", "Aruba", "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados", "Belarus", "Belgium", "Belize", "Benin", "Bermuda", "Bhutan", "Bolivia", "Bosnia &amp; Herzegovina", "Botswana", "Bouvet Island", "Brazil", "British Indian Ocean Territory", "British Virgin Islands", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia", "Cameroon", "Canada", "Cape Verde", "Cayman Islands", "Central African Republic", "Chad", "Chile", "China", "Christmas Island", "Cocos (Keeling) Islands", "Colombia", "Comoros", "Congo - Brazzaville", "Congo - Kinshasa", "Cook Islands", "Costa Rica", "Côte d’Ivoire", "Croatia", "Cuba", "Cyprus", "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador", "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Ethiopia", "Falkland Islands", "Faroe Islands", "Fiji", "Finland", "France", "French Guiana", "French Polynesia", "French Southern Territories", "Gabon", "Gambia", "Georgia", "Germany", "Ghana", "Gibraltar", "Greece", "Greenland", "Grenada", "Guadeloupe", "Guam", "Guatemala", "Guernsey", "Guinea", "Guinea-Bissau", "Guyana", "Haiti", "Heard &amp; McDonald Islands", "Honduras", "Hong Kong SAR China", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq", "Ireland", "Isle of Man", "Israel", "Italy", "Jamaica", "Japan", "Jersey", "Jordan", "Kazakhstan", "Kenya", "Kiribati", "Kuwait", "Kyrgyzstan", "Laos", "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania", "Luxembourg", "Macau SAR China", "Macedonia", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta", "Marshall Islands", "Martinique", "Mauritania", "Mauritius", "Mayotte", "Mexico", "Micronesia", "Moldova", "Monaco", "Mongolia", "Montenegro", "Montserrat", "Morocco", "Mozambique", "Myanmar (Burma)", "Namibia", "Nauru", "Nepal", "Netherlands", "New Caledonia", "New Zealand", "Nicaragua", "Niger", "Nigeria", "Niue", "Norfolk Island", "Northern Mariana Islands", "North Korea", "Norway", "Oman", "Pakistan", "Palau", "Palestinian Territories", "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Pitcairn Islands", "Poland", "Portugal", "Qatar", "Réunion", "Romania", "Russia", "Rwanda", "Samoa", "San Marino", "São Tomé &amp; Príncipe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles", "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia", "South Africa", "South Georgia &amp; South Sandwich Islands", "South Korea", "Spain", "Sri Lanka", "St. Barthélemy", "St. Helena", "St. Kitts &amp; Nevis", "St. Lucia", "St. Martin", "St. Pierre &amp; Miquelon", "St. Vincent &amp; Grenadines", "Sudan", "Suriname", "Svalbard &amp; Jan Mayen", "Swaziland", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania", "Thailand", "Timor-Leste", "Togo", "Tokelau", "Tonga", "Trinidad &amp; Tobago", "Tunisia", "Turkey", "Turkmenistan", "Turks &amp; Caicos Islands", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates", "United Kingdom", "United States", "Uruguay", "U.S. Outlying Islands", "U.S. Virgin Islands", "Uzbekistan", "Vanuatu", "Vatican City", "Venezuela", "Vietnam", "Wallis &amp; Futuna", "Western Sahara", "Yemen", "Zambia", "Zimbabwe"],
        allCurrencies: ["Afghan Afghani", "Albanian Lek", "Algerian Dinar", "Angolan Kwanza", "Argentine Peso", "Armenian Dram", "Aruban Florin", "Australian Dollar", "Azerbaijani Manat", "Azerbaijani Manat (1993–2006)", "Bahamian Dollar", "Bahraini Dinar", "Bangladeshi Taka", "Barbadian Dollar", "Belarusian Ruble", "Belize Dollar", "Bermudan Dollar", "Bhutanese Ngultrum", "Bolivian Boliviano", "Bosnia-Herzegovina Convertible Mark", "Botswanan Pula", "Brazilian Real", "British Pound", "Brunei Dollar", "Bulgarian Lev", "Burmese Kyat", "Burundian Franc", "CFP Franc", "Cambodian Riel", "Canadian Dollar", "Cape Verdean Escudo", "Cayman Islands Dollar", "Chilean Peso", "Chinese Yuan", "Colombian Peso", "Comorian Franc", "Congolese Franc", "Costa Rican Colón", "Croatian Kuna", "Cuban Peso", "Czech Republic Koruna", "Danish Krone", "Djiboutian Franc", "Dominican Peso", "East Caribbean Dollar", "Egyptian Pound", "Equatorial Guinean Ekwele", "Eritrean Nakfa", "Estonian Kroon", "Ethiopian Birr", "Euro", "Falkland Islands Pound", "Fijian Dollar", "Gambian Dalasi", "Georgian Kupon Larit", "Georgian Lari", "Ghanaian Cedi", "Gibraltar Pound", "Guatemalan Quetzal", "Guinean Franc", "Guyanaese Dollar", "Haitian Gourde", "Honduran Lempira", "Hong Kong Dollar", "Hungarian Forint", "Icelandic Króna", "Indian Rupee", "Indonesian Rupiah", "Iranian Rial", "Iraqi Dinar", "Israeli New Sheqel", "Jamaican Dollar", "Japanese Yen", "Jordanian Dinar", "Kazakhstani Tenge", "Kenyan Shilling", "Kuwaiti Dinar", "Kyrgystani Som", "Laotian Kip", "Latvian Lats", "Lebanese Pound", "Lesotho Loti", "Liberian Dollar", "Libyan Dinar", "Lithuanian Litas", "Macanese Pataca", "Macedonian Denar", "Malagasy Ariary", "Malawian Kwacha", "Malaysian Ringgit", "Maldivian Rufiyaa", "Mauritanian Ouguiya", "Mauritian Rupee", "Mexican Peso", "Moldovan Leu", "Mongolian Tugrik", "Moroccan Dirham", "Mozambican Metical", "Myanmar Kyat", "Namibian Dollar", "Nepalese Rupee", "Netherlands Antillean Guilder", "New Taiwan Dollar", "New Zealand Dollar", "Nicaraguan Córdoba (1988–1991)", "Nigerian Naira", "North Korean Won", "Norwegian Krone", "Omani Rial", "Pakistani Rupee", "Panamanian Balboa", "Papua New Guinean Kina", "Paraguayan Guarani", "Peruvian Nuevo Sol", "Philippine Peso", "Polish Zloty", "Qatari Rial", "Rhodesian Dollar", "Romanian Leu", "Romanian Leu (1952–2006)", "Russian Ruble", "Rwandan Franc", "Salvadoran Colón", "Samoan Tala", "Saudi Riyal", "Serbian Dinar", "Seychellois Rupee", "Sierra Leonean Leone", "Singapore Dollar", "Slovak Koruna", "Solomon Islands Dollar", "Somali Shilling", "South African Rand", "South Korean Won", "Sri Lankan Rupee", "St. Helena Pound", "Sudanese Pound", "Surinamese Dollar", "Swazi Lilangeni", "Swedish Krona", "Swiss Franc", "Syrian Pound", "São Tomé &amp; Príncipe Dobra", "Tajikistani Somoni", "Tanzanian Shilling", "Thai Baht", "Tongan Paʻanga", "Trinidad &amp; Tobago Dollar", "Tunisian Dinar", "Turkish Lira", "Turkish Lira (1922–2005)", "Turkmenistani Manat (1993–2009)", "US Dollar", "Ugandan Shilling", "Ukrainian Hryvnia", "United Arab Emirates Dirham", "Uruguayan Peso", "Uzbekistani Som", "Vanuatu Vatu", "Venezuelan Bolívar", "Venezuelan Bolívar (1871–2008)", "Vietnamese Dong", "WIR Euro", "WIR Franc", "West African CFA Franc", "Yemeni Rial", "Zambian Kwacha (1968–2012)", "Zimbabwean Dollar (1980–2008)"],
        allPages: ["Home", "About Us", "Terms and Conditions"],
        allDomains: ["domain1.com", "domain3.com", "domain3.com"],
        homePage: 3,
        selectedDomain: 2,
        allowCountries: [],
        enableLanguageDropdown: 1,
        defaultCurrency: 3,
        allowCurrencies: [],
        generalContactEmailAddress: '',
        salesContactEmailAddress: '',
        supportContactEmailAddress: '',
        customContactEmailAddress: '',
        catalogLayout: 2,
        productsPerPage: [5,10,20,50],
        allowAllProducts: 1,
        catalogSortBy: [],
        defaultCatalogSortBy: 1,
        useCategoryCanonicalLink: 1,
        productPlaceholder: '',
        enableProductReviews: 1,
        allowGuestReviews: 0,
        useCategoriesPathForUrl: 1,
        useProductCanonicalLink: 1,
        displayTax: 1,
        hidePricesForNonLoggedIn: 0,
        displayOutOfStockProducts: 1,
        displayStockNumberOnStorefront: 0,
        enableBackorders: 1,
        outOfStockThreshold: 0,
        enableOrderEmail: 1,
        sendOrderEmailCopyTo: '',
        orderEmailSender: 1,
        enableInvoiceEmail: 1,
        sendInvoiceCopyTo: '',
        invoiceEmailSender: 1,
        enableShipmentEmails: 1,
        sendShipmentEmailCopyTo: '',
        shipmentEmailSender: 1,
        enableRefundEmails: 1,
        sendRefundEmailCopyTo: '',
        refundEmailSender: 1,
        enableTax: 1,
        taxRateBasedOn: 1,
        taxCalculationBasedOn: 1,
        discountTaxCalculation: 1,
        enableCart: 1,
        showTaxPriceCart: 1,
        allowGuestCheckout: 1,
        enableAddressAutocomplete: 1,
        minimumOrderAmount: 5.00,
        termsAndConditionsOnCheckout: '',
        defaultCustomerGroup: 1,
        enableWelcomeEmail: 1,
        welcomeEmailSender: 1,
        enableSignUpConfirmatiionEmail: 1,
        redirectToDashboardAfterLogin: 1,
        adminLifetimeSeconds: 3600,
        minifyHtml: 0,
        minifyJavascript: 0,
        minifyCss: 0,
        mergeHtml: 0,
        mergeJavascript: 0,
        mergeCss: 0,
      }
];
const paymentsData = [
    {
        id: 1,
        paymentTitle: 'Stripe',
        enabled: 1,
        modes: ["Live","SandBox"],
        selectedMode: 1,
        livePublishableKey: '',
        liveSecretApiKey: '',
        liveWebhookSigningSecret: '',
        sandBoxPublishableKey: '',
        sandboxSecretApiKey: '',
        sandboxWebhooksSigningSecret: '',
        allowedCountries: [1,2],
        stripePayments: [
            {
                id: 1,
                stripePaymentTite: 'Card Payments',
                methodTitle: '',
                enabled: 0,
            },
            {
                id: 2,
                stripePaymentTite: 'Apple Pay',
                methodTitle: '',
                enabled: 0,
            },
            {
                id: 3,
                stripePaymentTite: 'Ali Pay',
                methodTitle: '',
                enabled: 0,
            },
            {
                id: 4,
                stripePaymentTite: 'Stripe Subscriptions',
                methodTitle: '',
                enabled: 0,
            },
            {
                id: 5,
                stripePaymentTite: 'WeChat',
                methodTitle: '',
                enabled: 0,
            },
        ],
        sortOrder: 0,
    },
    {
        id: 2,
        paymentTitle: 'PayPal',
        selected: false,
        enabled: 0,
        modes: ["Live","SandBox"],
        selectedMode: 1,
        methodTitle: '',
        merchantAccountEmailAddress: '',
        apiUsername: '',
        apiPassword: '',
        apiSignature: '',
        enablePaypalCredit: 0,
        enableGuestCheckout: 0,
        allowedCountries: [1,2],
        sortOrder: 0,
    },
    {
        id: 3,
        paymentTitle: 'Payment On Account',
        selected: false,
        enabled: 0,
        methodTitle: '',
        allowedCountries: [1,2],
        minimumOrderAmount: '',
        maximumOrderAmount: '',
        sortOrder: 0,
    }
];
export { configData, paymentsData };
